// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {features} from '../models';

export function Greet(arg1:string):Promise<string>;

export function Quit():Promise<void>;

export function ReadFile(arg1:string):Promise<string>;

export function SearchJishoWord(arg1:string):Promise<features.JishoResponse>;
